[tool.poetry]
name = "plant-traits"
version = "0.1.0"
description = ""
authors = ["Agustin Sanchez"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
